// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Note: Firebase is not yet integrated. Uncomment when adding firebase_core dependency.
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// FirebaseOptions class (placeholder until Firebase is integrated)
class FirebaseOptions {
  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String storageBucket;
  final String? authDomain;
  final String? iosBundleId;
  final String? measurementId;

  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    required this.storageBucket,
    this.authDomain,
    this.iosBundleId,
    this.measurementId,
  });
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2G6guarI4iOIm8jsLbka2VvmLxyTzzM',
    appId: '1:933164665912:android:cce528299b795fef176acd',
    messagingSenderId: '933164665912',
    projectId: 'kids-learning-app-5f3af',
    storageBucket: 'kids-learning-app-5f3af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEACAnpexy3Aby4hqv8qm-LSsblayD4xU',
    appId: '1:933164665912:ios:6682282778a71af4176acd',
    messagingSenderId: '933164665912',
    projectId: 'kids-learning-app-5f3af',
    storageBucket: 'kids-learning-app-5f3af.firebasestorage.app',
    iosBundleId: 'com.example.sdkSetup',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQSSXbpt1Tb6SaQDOuv1N-S2T_pBGbnNE',
    appId: '1:933164665912:web:66a57d7b48f3a13b176acd',
    messagingSenderId: '933164665912',
    projectId: 'kids-learning-app-5f3af',
    authDomain: 'kids-learning-app-5f3af.firebaseapp.com',
    storageBucket: 'kids-learning-app-5f3af.firebasestorage.app',
    measurementId: 'G-XVVDY3PQCT',
  );
}
